title: Vacation-30A - Santa Rosa Beach, Florida
description: Discover everything 30A has to offer! From the best vacation spots in Santa Rosa Beach, Florida, to events, tips, and hidden gems along Florida’s Emerald Coast.
show_downloads: false
google_analytics: G-FW8EF8CNPM
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
author: "Teemoney11"
keywords: "30A, Vacation, Santa Rosa Beach, Florida, Florida's Emerald Coast"
sass:
  style: compressed
